**Programmer:** python_scripts (Abhijith Warrier)

**PYTHON SCRIPT TO _SIMPLIFY MODEL EVALUATION USING CROSS-VALIDATION (CV)_. 📊🤖⚡️**

This script demonstrates how to apply **k-Fold Cross-Validation** to evaluate models more reliably than a single train/test split.

You’ll also compare Logistic Regression with Random Forest to see how CV highlights performance differences.

---

### **📦 Import Libraries**

In [1]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

---

### **🧩 Load Dataset & Train/Test Split**

In [2]:
data = load_wine()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

---

### **⚡ Apply Stratified 5-Fold Cross-Validation**

In [4]:
model = LogisticRegression(max_iter=10000)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(model, X_train, y_train, cv=cv, scoring="accuracy")

print("Logistic Regression Fold Scores:", scores)
print("Mean Accuracy:", scores.mean())
print("Std Dev:", scores.std())

Logistic Regression Fold Scores: [0.93103448 0.96551724 1.         0.92857143 0.96428571]
Mean Accuracy: 0.9578817733990148
Std Dev: 0.02627976092285545


---

### **🌲 Compare with Random Forest**

In [5]:
rf = RandomForestClassifier(n_estimators=300, random_state=42)

rf_scores = cross_val_score(rf, X_train, y_train, cv=cv, scoring="accuracy")

print("Random Forest Fold Scores:", rf_scores)
print("RF Mean Accuracy:", rf_scores.mean())
print("RF Std Dev:", rf_scores.std())

Random Forest Fold Scores: [0.93103448 1.         1.         1.         0.96428571]
RF Mean Accuracy: 0.9790640394088669
RF Std Dev: 0.027713464392187602


---

### **📊 Optional: Cross-Validated Predictions**

In [6]:
y_pred_cv = cross_val_predict(rf, X_train, y_train, cv=cv)
print("\nConfusion Matrix (CV Predictions):")
print(confusion_matrix(y_train, y_pred_cv))


Confusion Matrix (CV Predictions):
[[47  0  0]
 [ 1 54  2]
 [ 0  0 38]]


---

### **🎯 Summary**

- CV reduces result variance
- Helps compare models fairly
- Prevents overfitting to one split
- Uses ALL data for training/testing in cycles

---